apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: bc1
          image: srilalithac/blue:latest
          ports:
            - containerPort: 80
