apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: gc1
          image: srilalithac/green:latest
          ports:
            - containerPort: 80
